EMAIL_ID = 'saranshmanu@yahoo.co.in'
EMAIL_PASSWORD = 'password'
JWT_SECRET = "THIS_IS_THE_JWT_SECRET"
JWT_ALGORITHM = ['HS256']
JWT_EXPIRATION_DURATION = 1000
DATABASE_LINK = "mongodb://saransh.xyz"
NAME_OF_THE_DATABASE = "USER_DATABASE"